// <auto-generated />
using System;
using IglesiaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IglesiaAPI.Migrations
{
    [DbContext(typeof(IglesiaDBContext))]
    [Migration("20260530022214_InicialProduccionMySql")]
    partial class InicialProduccionMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IglesiaAPI.Models.Celula", b =>
                {
                    b.Property<int>("CelulaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "celulaId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CelulaID"));

                    b.Property<int?>("CreadoPorID")
                        .HasColumnType("int");

                    b.Property<string>("DiaReunion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "diaReunion");

                    b.Property<string>("HoraReunion")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "horaReunion");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    b.Property<int?>("MiembroID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "miembroId");

                    b.Property<string>("NombreCelula")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombreCelula");

                    b.HasKey("CelulaID");

                    b.HasIndex("CreadoPorID");

                    b.HasIndex("LocalidadID");

                    b.HasIndex("MiembroID");

                    b.ToTable("Celulas");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Cuenta", b =>
                {
                    b.Property<int>("CuentaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "cuentaId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CuentaID"));

                    b.Property<int?>("CreadoPorID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "creadoPorId");

                    b.Property<bool>("EsNacional")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "esNacional");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombreCuenta");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)")
                        .HasAnnotation("Relational:JsonPropertyName", "saldo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo");

                    b.HasKey("CuentaID");

                    b.HasIndex("CreadoPorID");

                    b.HasIndex("LocalidadID");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Inventario", b =>
                {
                    b.Property<int>("InventarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "inventarioId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InventarioID"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "cantidad");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "categoria");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "estado");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaAdquisicion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaRegistro");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "imagenUrl");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "modelo");

                    b.Property<string>("NoSerie")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "noSerie");

                    b.Property<string>("NombreArticulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombreArticulo");

                    b.Property<string>("Responsable")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "responsable");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "ubicacion");

                    b.Property<int?>("UsuarioID_Registra")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "usuarioid_Registra");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "valorUnitario");

                    b.HasKey("InventarioID");

                    b.HasIndex("LocalidadID");

                    b.HasIndex("UsuarioID_Registra");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Localidad", b =>
                {
                    b.Property<int>("LocalidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LocalidadID"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "direccion");

                    b.Property<DateTime?>("FechaFundacion")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaFundacion");

                    b.Property<string>("NombreLocalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombreLocalidad");

                    b.HasKey("LocalidadID");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Miembro", b =>
                {
                    b.Property<int>("MiembroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "miembroId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MiembroID"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "categoria");

                    b.Property<string>("Ciudad")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "ciudad");

                    b.Property<string>("Conyugue")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "conyugue");

                    b.Property<string>("Correo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "correo");

                    b.Property<int?>("CreadoPorID")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorUsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "direccion");

                    b.Property<bool>("EsSellado")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "esSellado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "estado");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "estadoCivil");

                    b.Property<DateTime?>("FechaBautizado")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaBautizado");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaNacimiento");

                    b.Property<string>("FotoPath")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "fotoPath");

                    b.Property<string>("Hijos")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "hijos");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    b.Property<string>("Lugar")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lugar");

                    b.Property<string>("Madre")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "madre");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "nacionalidad");

                    b.Property<string>("NivelAcademico")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "nivelAcademico");

                    b.Property<string>("No_registro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "noRegistro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombreCompleto");

                    b.Property<string>("NumeroDoc")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "numeroDoc");

                    b.Property<string>("Padre")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "padre");

                    b.Property<string>("Profesion")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "profesion");

                    b.Property<string>("Provincia")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "provincia");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "sexo");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "telefono");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "tipoDocumento");

                    b.HasKey("MiembroID");

                    b.HasIndex("CreadoPorUsuarioID");

                    b.HasIndex("LocalidadID");

                    b.ToTable("Miembros");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Movimiento", b =>
                {
                    b.Property<int>("MovimientoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "movimientoId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MovimientoID"));

                    b.Property<int>("CuentaID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "cuentaId");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<bool>("EsEditable")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "esEditable");

                    b.Property<string>("EstadoValidacion")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "estadoValidacion");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaMovimiento");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaRegistro");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    b.Property<string>("LoteReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "loteReferencia");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)")
                        .HasAnnotation("Relational:JsonPropertyName", "monto");

                    b.Property<string>("NoReferencia")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "noReferencia");

                    b.Property<string>("NoSerial")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "noSerial");

                    b.Property<bool>("TieneSolicitudEdicion")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "tieneSolicitudEdicion");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "tipoMovimiento");

                    b.Property<int?>("UsuarioID_Aprobador")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "usuarioId_Aprobador");

                    b.Property<int>("UsuarioID_Creador")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "usuarioId_Creador");

                    b.Property<string>("VoucherUrl")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "voucherUrl");

                    b.HasKey("MovimientoID");

                    b.HasIndex("CuentaID");

                    b.HasIndex("LocalidadID");

                    b.HasIndex("UsuarioID_Creador");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("IglesiaAPI.Models.RegistroSecretaria", b =>
                {
                    b.Property<int>("RegistroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "registroId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegistroID"));

                    b.Property<int?>("CreadoPorID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "creadoPorId");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "descripcion");

                    b.Property<string>("DocumentoURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "documentoUrl");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("DATE")
                        .HasAnnotation("Relational:JsonPropertyName", "fechaRegistro");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "tipoRegistro");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasAnnotation("Relational:JsonPropertyName", "titulo");

                    b.HasKey("RegistroID");

                    b.HasIndex("CreadoPorID");

                    b.HasIndex("LocalidadID");

                    b.ToTable("RegistrosSecretaria");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "usuarioId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<int>("LocalidadID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "localidadId");

                    b.Property<int?>("MiembroID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "miembroId");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "nombreUsuario");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "rol");

                    b.HasKey("UsuarioID");

                    b.HasIndex("LocalidadID");

                    b.HasIndex("MiembroID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Celula", b =>
                {
                    b.HasOne("IglesiaAPI.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorID");

                    b.HasOne("IglesiaAPI.Models.Localidad", "Localidad")
                        .WithMany("Celulas")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IglesiaAPI.Models.Miembro", "Miembro")
                        .WithMany()
                        .HasForeignKey("MiembroID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPor");

                    b.Navigation("Localidad");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Cuenta", b =>
                {
                    b.HasOne("IglesiaAPI.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorID");

                    b.HasOne("IglesiaAPI.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Inventario", b =>
                {
                    b.HasOne("IglesiaAPI.Models.Localidad", "Localidad")
                        .WithMany("Inventarios")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IglesiaAPI.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("UsuarioID_Registra");

                    b.Navigation("CreadoPor");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Miembro", b =>
                {
                    b.HasOne("IglesiaAPI.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioID");

                    b.HasOne("IglesiaAPI.Models.Localidad", "Localidad")
                        .WithMany("Miembros")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Movimiento", b =>
                {
                    b.HasOne("IglesiaAPI.Models.Cuenta", "Cuenta")
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IglesiaAPI.Models.Localidad", "Localidad")
                        .WithMany("Movimientos")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IglesiaAPI.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("UsuarioID_Creador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Cuenta");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("IglesiaAPI.Models.RegistroSecretaria", b =>
                {
                    b.HasOne("IglesiaAPI.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IglesiaAPI.Models.Localidad", "Localidad")
                        .WithMany("RegistrosSecretaria")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Usuario", b =>
                {
                    b.HasOne("IglesiaAPI.Models.Localidad", "Localidad")
                        .WithMany("Usuarios")
                        .HasForeignKey("LocalidadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IglesiaAPI.Models.Miembro", "Miembro")
                        .WithMany("Usuarios")
                        .HasForeignKey("MiembroID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Localidad");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Localidad", b =>
                {
                    b.Navigation("Celulas");

                    b.Navigation("Inventarios");

                    b.Navigation("Miembros");

                    b.Navigation("Movimientos");

                    b.Navigation("RegistrosSecretaria");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("IglesiaAPI.Models.Miembro", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
